apiVersion: operator.dash0.com/v1alpha1
kind: Dash0OperatorConfiguration
metadata:
  name: dash0-operator-configuration
spec:
  export:
    dash0:
      endpoint: ${DASH0_OTLP_ENDPOINT}
      authorization:
        token: ${DASH0_TOKEN}
